version: "2"
services:
  go1:
    image: golang:1.13.0-alpine3.10
    command: go run main.go
    working_dir: /go1
    volumes:
      - ./go1:/go1
  go2:
    image: golang:1.13.0-alpine3.10
    command: ./wait.sh
    working_dir: /go2
    volumes:
      - ./go2:/go2